

// try {
//     let x = undefined;
//     console.log(x[0]);
// } catch {
//     console.log('Error in catch');
// } finally {
//     console.log('Finally always gets executed');
// }


try {
    console.log('Hello');
    console.log(a);
} catch {
    console.log('Handled');
}